my_list = []
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
print(my_list)
my_list[1] = 15
my_list.extend([50,60,70])
print(my_list)
my_list.pop()
print(my_list)
sorted_list = sorted(my_list)
print(sorted_list)
index_of_30 = my_list.index(30)
print(index_of_30)